config/routes.rb
Rails.application.routes.draw do
  root 'matches#index'     # 'Favorites' one option; based on assumption that user has favorites if they have a login?
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  resources :favorites

  resources :shelters do
    resources :pets
  end

  resources :matches, only:[:index, :show, :find]
  post 'matches/find', to: 'matches#find'

end

app/models/shelter.rb
class Shelter < ActiveRecord::Base

    has_many :pets
    has_many :users
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
    before_action :find_shelter, only: [:show, :edit, :update, :destroy]
    authorize_resource
    def index
        @shelters = Shelter.all
    end

    def show

    end

    def edit

    end

    def new
        @shelter = Shelter.new()
    end

    def create
         @shelter = Shelter.new(shelter_params)
        if @shelter.save
            redirect_to @shelter
        else
            show :new
        end
    end

    def update
        if (@shelter.update(shelter_params))
            redirect_to @shelter
        else
            show :edit
        end
    end

    def destroy
        @shelter.destroy
        redirect_to shelters_url
    end

    private

    def shelter_params
        params.require(:shelter).permit(:name, :address,  :phone, :email, :banner, :story)
    end
    def find_shelter
            @shelter = Shelter.find(params[:id])
    end
end

app/views/shelters/_form.html.erb
<% if @shelter.errors.any? %>
    <ul>
    <% @shelter.errors.full_messages.each do |err| %>
        <li><%= err %></li>
    <% end %>
    </ul>
<% end %>
<%= form_for @shelter do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

        <%= f.label :story %>
    <%= f.text_area :story %>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.label :phone %>
    <%= f.text_field :phone %>

        <%= f.label :email %>
    <%= f.text_field :email %>

        <%= f.label :banner %>
    <%= f.text_field :banner %>

    <%= f.submit  class: "button "%>
<% end %>

app/views/shelters/edit.html.erb
<h1>Update Shelter Details</h1>
<%= render 'form' %>

app/views/shelters/index.html.erb
<h1>Shelters Directory
<% if can? :create, @shelter %>
 - <small><%= link_to 'add', new_shelter_path%></small>
 <% end %></h1>

<% @shelters.each do |shelter| %>
<div class='row '>
    <div class='large-12 columns clearfix'>
         <h3><%= link_to shelter.name, shelter %> </h3>
         <ul >
             <li><%= shelter.address %></li>
              <li><%= shelter.phone %></li>
              <li><%= shelter.email %></li>
         </ul>

    </div>

</div>
<% end %>

app/views/shelters/new.html.erb
<h1>Register New Shelter </h1>
<%= render 'form' %>

app/views/shelters/show.html.erb
<h1>
    Welcome to
    <%= @shelter.name %></h1>
    <img src='<%=  "http://lorempixel.com/300/300/nature/" %>
    ' class=' medium-3 right'/>
    <h3>About us</h3>
<div class='medium-8 clearfix puppy-bio' >

    <p>
        <%= @shelter.story %>
          </p>
</div>
<div class='medium-3 panel right'>

    <h3>Details</h3>
    <ul >
        <li > <strong>Address:</strong>
            <%= @shelter.address %></li>
        <li > <strong>Phone:</strong>
            <%= @shelter.phone %></li>
        <li >
            <strong>Email:</strong>
            <%= @shelter.email %></li>
    </ul>
    <%  if can? :update, @shelter %>
    <%= link_to 'Edit', edit_shelter_path(@shelter), class: 'button tiny radius' %>
    <% end %>
    <% if can? :delete, @shelter %>
    <%= link_to 'Delete', @shelter, method: :delete, data: {confirm: 'Are you sure you want to delete this shelter?'}, class: 'button tiny radius' %>
    <% end %>
</div>
<div class=' medium-8 columns  left shelter-pets'>
<h3>Meet our family
<% if can? :update, @shelter %>
 - <small><%= link_to 'add', new_shelter_pet_path(@shelter) %></small>
 <% end %>
 </h3>
<% @shelter.pets.each do |pet| %>
    <div class='medium-4 clearfix  columns left' >
        <img src='<%= pet.picture_url || "http://lorempixel.com/300/300/animals/8/" %>'
         class='tiny th' />
         <ul class=''>
              <li><%= link_to pet.name, [@shelter,pet] %></li>
              <li><%= pet.color %> <%= pet.breed %></li>
             <li><%= pet.sex[0].upcase %> - <%= pet.age %></li>
         </ul>
    </div>
<% end %>
</div>