config/routes.rb
Rails.application.routes.draw do
  root 'matches#index'     # 'Favorites' one option; based on assumption that user has favorites if they have a login?
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  resources :favorites

  resources :shelters do
    resources :pets
  end

  resources :matches, only:[:index, :show, :find]
  post 'matches/find', to: 'matches#find'

end

app/views/login_forms/_sign_in.html.erb
<div class='sign-in-form' id='sign-in-form'>
<h2>Sign In</h2>
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
<%= f.label :email %>
<%= f.email_field :email, :autofocus => true %>
<%= f.label :password %>
<%= f.password_field :password %>
<% if devise_mapping.rememberable? -%>
<%= f.check_box :remember_me %> <%= f.label :remember_me %>
<% end -%>
<br>
<div id='sign-in-errors'>

</div>
<%= f.submit "Sign in", :class => 'button' %>
<% end %>
<a href='#'  data-reveal-id="sign-up-modal">Sign up</a>
</div>




<script type="text/javascript">


</script>

app/views/login_forms/_sign_up.html.erb
<div class='sign-up-form' id='sign-up-form'>
<h2>Sign Up</h2>
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
<%= devise_error_messages! %>
<%= f.label :first_name %>
 <%= f.text_field :first_name,   :autofocus => true %>
 <%= f.label :last_name %>
<%= f.text_field :last_name %>
<%= f.label :email %>
<%= f.email_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<div id='sign-up-errors'>

</div>


</div>
<%= f.submit "Sign up", :class => 'button' %>
<% end %>
<a href='#'  data-reveal-id="sign-in-modal">Sign in</a>
</div>

<script type="text/javascript">

</script>