config/routes.rb
Rails.application.routes.draw do
  root 'matches#index'     # 'Favorites' one option; based on assumption that user has favorites if they have a login?
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  resources :favorites

  resources :shelters do
    resources :pets
  end

  resources :matches, only:[:index, :show, :find]
  post 'matches/find', to: 'matches#find'

end

app/models/pet.rb
class Pet < ActiveRecord::Base

    belongs_to :shelter
    has_many :favorites
    # excellent use of scopes!
    scope :dog, -> { where(pet_type: 'dog') }
    scope :cat, -> { where(pet_type: 'cat') }
    scope :other, -> { where(pet_type: 'other') }


end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
    before_action :find_pet, only: [:show, :edit, :update, :destroy]
    authorize_resource

    def index
        @pets = Pet.all()

    end

    def show
        @pet = Pet.find(params[:id])
    end

    def edit

    end

    def new
        @shelter = Shelter.find(params[:shelter_id])
        @pet = Pet.new()
    end

    def create
        @shelter = Shelter.find(params[:shelter_id])
        @pet = @shelter.pets.new(pet_params)

        if @pet.save?
            redirect_to @pet
        else
            show :new
        end
    end

    def update

        if (@pet.update(pet_params))
            redirect_to @pet
        else
            show :edit
        end


    end



    private

    def pet_params
        params.require(:pet).permit(:name, :breed,  :sex, :color, :size, :age, :energy, :kid_friendly, :bio, :picture_url)
    end
    def find_pet
        if !params[:shelter_id]
            @pet = Pet.find(params[:id])
        else
            @pet = Pet.find_by(shelter_id: params[:shelter_id], id: params[:id])
            @shelter = @pet.shelter
        end

    end

end

app/views/pets/_form.html.erb
<% if @pet.errors.any? %>
    <ul>
    <% @pet.errors.full_messages.each do |err| %>
        <li><%= err %></li>
    <% end %>
    </ul>
<% end %>
<%= form_for [@shelter,@pet] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :breed %>
    <%= f.text_field :breed %>

    <%= f.label :sex %>
    <%= f.text_field :sex %>

        <%= f.label :size %>
    <%= f.text_field :size %>

        <%= f.label :color %>
    <%= f.text_field :color %>

        <%= f.label :age %>
    <%= f.text_field :age %>

        <%= f.label :energy %>
    <%= f.text_field :energy %>


    <%= f.check_box :kid_friendly %>
        <%= f.label :kid_friendly %>


        <%= f.label :picture_url %>
    <%= f.text_field :picture_url %>



    <%= f.label :bio %>
    <%= f.text_area :bio %>

    <%= f.submit  class: "button "%>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit <%= @pet.name %> Details </h1>
<%= render 'form' %>

app/views/pets/index.html.erb
<h1>Pets Index </h1>

<% @pets.each do |pet| %>
<div class='row '>
    <div class='panel large-12 columns clearfix'>
        <img src='<%= pet.picture_url || "http://lorempixel.com/300/300/animals/8/" %>'
         class='left puppy thumb'/>
         <h3><%= link_to pet.name, pet %> <small><%= pet.color %> <%= pet.breed %></small></h3>
         <ul class='puppy-details'>
             <li><%= pet.sex %> - <%= pet.age %> old </li>
            <li><%= "Kid Friendly!" if pet.kid_friendly == true%></li>
         </ul>

    </div>

</div>
<% end %>

app/views/pets/new.html.erb
<h1>Add a new pet to our family! </h1>
<%= render 'form' %>

app/views/pets/show.html.erb
<h1>
    Meet
    <%= @pet.name.capitalize %></h1>
    <div class='medium-4 columns right '>
        <img src='<%= @pet.picture_url || "http://lorempixel.com/300/300/animals/8/" %>
    ' class='puppy large'/>
    <br> <!-- yeah br tag, i am over this stupid button placement -->
    <% if can? :update, @pet %>
    <%= link_to 'Edit', edit_shelter_pet_path(@shelter, @pet), class: 'button tiny radius' %>
    <% end %>
    <% if can? :delete, @pet %>
    <%= link_to 'Delete', shelter_pet_path(@shelter,@pet), method: :delete, data: {confirm: 'Are you sure you want to delete this pet?'}, class: 'button tiny radius' %>
    <% end %>
</div>
<div class='medium-8 columns left puppy-bio' >

    <h3>My story</h3>
    <p>
        <%= @pet.bio %>
          </p>
          <div class='puppy-information'>
          <h3>Puppy Details</h3>
    <ul >
        <li class='medium-4 column left'> <strong>Name:</strong>
            <%= @pet.name %></li>
        <li class='medium-4 column left'> <strong>Breed:</strong>
            <%= @pet.breed %></li>
        <li class='medium-4 column left'>
            <strong>Sex:</strong>
            <%= @pet.sex %></li>
        <li class='medium-4 column left'>
            <strong>Color:</strong>
            <%= @pet.color %></li>
        <li class='medium-4 column left'>
            <strong>Size:</strong>
            <%= @pet.size %></li>
        <li class='medium-4 column left'>
            <strong>Kid Friendly:</strong>
            <%= @pet.kid_friendly %></li>
        </ul>
</div>
</div>