config/routes.rb
Rails.application.routes.draw do
  root 'matches#index'     # 'Favorites' one option; based on assumption that user has favorites if they have a login?
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  resources :favorites

  resources :shelters do
    resources :pets
  end

  resources :matches, only:[:index, :show, :find]
  post 'matches/find', to: 'matches#find'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Best Friends Forever</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body >

 <nav class="top-bar" data-topbar>
          <ul class="title-area">

            <li class="name">
              <h1>
                <a href="/">
                  <img src='/assets/bff-logo.png' alt='bff logo'  class='logo'/> BFF
                </a>
              </h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
          </ul>

          <section class="top-bar-section">

            <ul class="right">
              <li class="divider"></li>
              <li ><%= link_to "Find Your Pet Match", matches_path %></li>
              <li class="divider"></li>
              <li ><%= link_to "Shelters", shelters_path %></li>
              <li class="divider"></li>
              <!-- Below = Secure signout link for current_user -->
              <% if current_user %>
              <li><%= link_to "Favorites (#{current_user.favorites.count})", favorites_path, id: "favorites-count" %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
              <% else %>
              <li><%= link_to "Favorites", favorites_path, id: 'favorites-count' %></li>
              <li> <a href="#" data-reveal-id="sign-in-modal">Sign In</a></li>
            <% end %>
            </ul>
          </section>
        </nav>
  <div id="sign-in-modal" class="reveal-modal remove-whitespace" data-reveal>
<div class="row">
  <%= render "login_forms/sign_in" %>
  <a class="close-reveal-modal">&#215;</a>
</div>
</div>

  <div id="sign-up-modal" class="reveal-modal remove-whitespace" data-reveal>
<div class="row">
  <%= render "login_forms/sign_up" %>
  <a class="close-reveal-modal">&#215;</a>
</div>
</div>


    <main class='content row'>
    <%= yield %>
  </main>
<footer class="footer">
  <div class="row">
    <div class="small-12 columns">
      <p class="slogan">Best Friends Finder - Making Life Long Relationships</p>
      <p class="links">
        <a href="#">Home</a>
        <a href="#">Blog</a>
        <a href="#">About</a>
        <a href="#">Faq</a>
        <a href="#">Contact</a>
      </p>
      <p class="copywrite">Coffeewrite © 2015</p>
    </div>
  </div>
</footer>
</body>
</html>

app/views/layouts/match_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Best Friends Forever</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body >

 <nav class="top-bar" data-topbar>
          <ul class="title-area">

            <li class="name">
              <h1>
                <a href="/">
                  <img src='/assets/bff-logo.png' alt='bff logo'  class='logo'/> BFF
                </a>
              </h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
          </ul>

          <section class="top-bar-section">

            <ul class="right">
              <li class="divider"></li>
              <li ><%= link_to "Find Your Pet Match", matches_path %></li>
              <li class="divider"></li>
              <li ><%= link_to "Shelters", shelters_path %></li>
              <li class="divider"></li>
              <!-- Below = Secure signout link for current_user -->
              <% if current_user %>
              <li><%= link_to "Favorites (#{current_user.favorites.count})", favorites_path, id: 'favorites-count' %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
              <% else %>
              <li><%= link_to "Favorites", favorites_path, id: 'favorites-count' %></li>
              <li class="divider"></li>
              <li id='sign-out-nav' class="hide"> <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
              <li id='sign-in-nav'> <a href="#" data-reveal-id="sign-in-modal">Sign In</a>
              </li>
            <% end %>
            </ul>
          </section>
        </nav>
  <div id="sign-in-modal" class="reveal-modal remove-whitespace" data-reveal>
<div class="row">
  <%= render "login_forms/sign_in" %>
  <a class="close-reveal-modal">&#215;</a>
</div>
</div>

  <div id="sign-up-modal" class="reveal-modal remove-whitespace" data-reveal>
<div class="row">
  <%= render "login_forms/sign_up" %>
  <a class="close-reveal-modal">&#215;</a>
</div>
</div>



    <%= yield %>


</body>
</html>